# Generated by Django 5.2.1 on 2025-05-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0002_product_description_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banners", models.JSONField(blank=True, default=list)),
                (
                    "featured_products",
                    models.ManyToManyField(blank=True, to="clothes.product"),
                ),
            ],
        ),
    ]
