# Generated by Django 5.2.1 on 2025-05-22 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0003_home"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Home",
        ),
    ]
