# Generated by Django 5.2.1 on 2025-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0004_delete_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
            ],
        ),
    ]
