# Generated by Django 5.2.1 on 2025-05-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0005_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
