# Generated by Django 5.2.1 on 2025-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
